FROM nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04

# update apt

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test -y\ 
    && apt-get update \
    && apt-get install python3.7 -y\
    && apt-get install libpython3.7 -y\
    && apt-get install g++-7 -y \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 \
    && update-alternatives --config gcc \
    && apt-get install -y cmake \
    && apt-get install -y python3-pip \
    && apt-get install -y python3.7-venv\
    && pip3 install cpplint\
    && apt-get install -y lcov \
    && apt-get install -y cppcheck \
    && apt-get install -y curl \
    && apt-get install -y unzip \
    && apt-get install -y doxygen \
    && apt-get install -y graphviz \
    && apt-get install -y clang-format

## install deep learning inside virtualenv
RUN mkdir /dl_env
RUN python3.7 -m venv /dl_env
ADD requirements.txt /dl_env
ADD torch-1.7.0-cp37-cp37m-manylinux1_x86_64.whl /dl_env
ADD spconv-1.2.1-cp37-cp37m-linux_x86_64_1804.whl /dl_env 

WORKDIR /dl_env
RUN . /dl_env/bin/activate\
    && pip install numpy\
    && pip install -r requirements.txt\
    && pip install torch-1.7.0-cp37-cp37m-manylinux1_x86_64.whl\
    && pip install spconv-1.2.1-cp37-cp37m-linux_x86_64_1804.whl

CMD ["echo", "Successfully load the docker image"]


